<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Quest2-VRC.Core\Quest2-VRC.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenRGB.NET" Version="3.1.1" />
  </ItemGroup>

</Project>
